### ISSUE TITLE
Consider migrating optimization for GetObjectNamesForType from Spring.Web.Mvc into Spring.Core

### ISSUE THREAD

**Issue by sbohlen** [spring-projects/spring-net#100]
The optimization strategy implemented in https://github.com/spring-projects/spring-net/commit/01d4db4e51903e65dd7926a6a5e6d48747f52366 could conceivably be moved into the core DI container so that all implementations could benefit from it.

**Comment by lahma** [comment]
I'm doing a rude experiment with closing this, like what stale bot does, but maybe more human as I will probably actually react to feedback. As this issue has been stale for so long, I'll close it. If it's still an issue you would like to pursue, we can definitely reopen. 

With limited resources this is just something that we need to do. Thank you for your understanding.
