### ISSUE TITLE
WCF Open Session In View support for NHibernate for lazy loading

### ISSUE THREAD

**Issue by ynauls** [spring-projects/spring-net#104]
Did this issue get any traction for Spring.NET 2.0 [SPRNET-317](https://jira.spring.io/browse/SPRNET-317)? The Jira issue sites a couple of useful links, (since the issue is old) I wanted to check if this is still the recommended solution in Spring's current state? [How to Implement Hibernate OpenSessionInView with WCF Services](http://forum.springframework.net/showthread.php?4636-How-to-Implement-Hibernate-OpenSessionInView-with-WCF-Services)?

**Comment by sbohlen** [comment]
There have been no improvements to this capability as part of the 2.0 release cycle, so for the time being the recommendations in that JIRA issue as well as the referenced forum posts are still the latest information/recommendation available.

That said, we'd be happy to entertain a PR that tries to address this for a post-2.0-GA release ... ;)

**Comment by ynauls** [comment]
@sbohlen, sounds good, I will take a peek.

**Comment by lahma** [comment]
I'm doing a rude experiment with closing this, like what stale bot does, but maybe more human as I will probably actually react to feedback. As this issue has been stale for so long, I'll close it. If it's still an issue you would like to pursue, we can definitely reopen. 

With limited resources this is just something that we need to do. Thank you for your understanding.
