### ISSUE TITLE
Spring.Web.Optimization integration in Spring.Web

### ISSUE THREAD

**Issue by djechelon** [spring-projects/spring-net#106]
Hello, I have a feature request to propose.

You all know about Web Optimization Framework. One of its features is bundle mapping for styles and scripts. It is currently done via code using the BundleTable class. For example:

```
        bundles.Add(new ScriptBundle("~/bundles/jquery").Include(
                    "~/Scripts/jquery-{version}.js"));

        bundles.Add(new ScriptBundle("~/bundles/jqueryval").Include(
                    "~/Scripts/jquery.validate*"));
```

More advanced users map bundles to their official (or project-supplied) CDN.

On my own, a few years ago, I have made an XML-based configuration of the bundles, so these could be changed without recompiling the application. I don't know about its real utility in common projects, because normal product lifecycles require that a change in the Javascript/CSS fileset (e.g. adding/changing version of Bootstrap) is treated as a **change** and it's easy for a project manager to require a code change to map the new JS/CSS bundle to a library.

Anyway I have created a parser that automatically maps bundles to the BundleTable according to the following syntax

```
<bundle xsi:type="StyleBundle" virtualPath="~/bundles/metro-style-dark-blue" cdnPath="http://some.cdn">
    <include>~/Content/themes/dark-blue.css</include>
</bundle>

<bundle xsi:type="StyleBundle" virtualPath="~/bundles/metroStyle">
    <include>~/Content/base.css</include>
    <include>~/Content/skeleton.css</include>
    <include>~/Content/layout.css</include>
</bundle>

<bundle xsi:type="ScriptBundle" virtualPath="~/bundles/jQuery">
    <include>~/Scripts/jquery-{version}.js</include>
    <include>~/Scripts/jquery-ui-{version}.js</include>
    <include>~/Scripts/jquery.easing.{version}.js</include>
    <include>~/Scripts/plugins.all.js</include>
    <!--<include>~/Scripts/jquery.address-{version}.js</include>-->
    <include>~/Scripts/selectivizr.js</include>
</bundle>
```

I do currently have defined an XML schema, a `ConfigurationSection` element and a utility class. Currently my implementation doesn't support transformations yet (very useful to add). I won't show for brevity.

In order to start the discussion, and later provide code, I would ask the Spring team if you are interested in adding support for `System.Web.Optimization` in the Spring context file, so that the developer can add bundles to the BundleTable according to a similar syntax in the web context file. That would be `automagically` activated by the Spring Web context once the proper tag is found in the XML.
(Similarly for code-based configuration).

Thank you for your time.

post scriptum: I read about the `bundles.config` file (that is supposed to do everything my implementation does) but I have found no information about it. My code was built about 3 years ago

**Comment by lahma** [comment]
I'm doing a rude experiment with closing this, like what stale bot does, but maybe more human as I will probably actually react to feedback. As this issue has been stale for so long, I'll close it. If it's still an issue you would like to pursue, we can definitely reopen. 

With limited resources this is just something that we need to do. Thank you for your understanding.
