### ISSUE TITLE
Misleading summary doc in AbstractPlatformTransactionManager.TransactionSynchronization

### ISSUE THREAD

**Issue by peto268** [spring-projects/spring-net#108]
In AbstractPlatformTransactionManager.TransactionSynchronization the summary should be:

Sets and gets when this transaction manager should activate the thread-bound transaction synchronization support. Default is **"never"**.

**Comment by lahma** [comment]
I'm doing a rude experiment with closing this, like what stale bot does, but maybe more human as I will probably actually react to feedback. As this issue has been stale for so long, I'll close it. If it's still an issue you would like to pursue, we can definitely reopen. 

With limited resources this is just something that we need to do. Thank you for your understanding.
