### ISSUE TITLE
spring2.0GA  error by mono-runtime 

### ISSUE THREAD

**Issue by mowan808** [spring-projects/spring-net#111]
ex	{System.TypeInitializationException: An exception was thrown by the type initializer for Spring.Context.Support.WebApplicationContext ---> System.NullReferenceException: Object reference not set to an instance of an object   at Spring.Context.Support.WebApplicationContext..cctor () [0x0005f] in /home/mowan/code/spring/spring.Web/Context/Support/WebApplicationContext.cs:166    --- End of inner exception stack trace --- at (wrapper dynamic-method) object._dynamic_Spring.Context.Support.WebApplicationContext..ctor (object[]) <IL 0x00038, 0x0013c> at Spring.Reflection.Dynamic.SafeConstructor.Invoke (object[]) [0x00008] in /home/mowan/code/spring/spring.core/Reflection/Dynamic/DynamicConstructor.cs:113 at Spring.Context.Support.ContextHandler/RootContextInstantiator.InvokeContextConstructor (System.Reflection.ConstructorInfo) [0x0002d] in /home/mowan/code/spring/spring.core/Context/Support/ContextHandler.cs:562 at Spring.Context.Support.ContextHandler/ContextInstantiator.InstantiateContext () [0x00039] in /home/mowan/code/spring/spring.core/Context/Support/ContextHandler.cs:507 at Spring.Context.Support.ContextHandler.InstantiateContext (Spring.Context.IApplicationContext,object,string,System.Type,bool,System.Collections.Generic.IList`1<string>) [0x0004d] in /home/mowan/code/spring/spring.core/Context/Support/ContextHandler.cs:350 at Spring.Context.Support.WebContextHandler.InstantiateContext (Spring.Context.IApplicationContext,object,string,System.Type,bool,System.Collections.Generic.IList`1<string>) [0x00078] in /home/mowan/code/spring/spring.Web/Context/Support/WebContextHandler.cs:123 at Spring.Context.Support.ContextHandler.Create (object,object,System.Xml.XmlNode) [0x000b9] in /home/mowan/code/spring/spring.core/Context/Support/ContextHandler.cs:288 }	System.TypeInitializationException

**Comment by mowan808** [comment]
run asp.net mvc4  error by mono 4.0

**Comment by sbohlen** [comment]
Unfortunately the MONO support in SPRNET isn't any longer being actively maintained (and has been unsupported for a number of years now).

We are still accepting pull-requests for MONO support, so if you can resolve the issue(s) we're happy to accept your fix(es) but MONO support is in a "use-at-your-own-risk" state and doesn't any longer undergo testing as part of the continuous integration process or the pre-release QA process that accompanies the rest of the SPRNET project.

I'm closing this issue for now, but as mentioned please do feel free to submit a pull request with any proposed changes to support MONO.
