### ISSUE TITLE
Is Spring.Web.Mvc 2.0 package being released soon?

### ISSUE THREAD

**Issue by ynauls** [spring-projects/spring-net#112]
@sbohlen, is there a schedule for the release of Spring.Web.Mvc 2.0 GA on Nuget?

**Comment by lahma** [comment]
@ynauls you should use package Spring.Web.Mvc3, Spring.Web.Mvc4 and Spring.Web.Mvc5. They have been updated for GA release. Spring.Web.Mvc is obsolete and Spring.NET 1.x series specific.
