### ISSUE TITLE
when spring.net support ASP.NET 5?

### ISSUE THREAD

**Issue by ynnuyonw** [spring-projects/spring-net#123]
when spring.net support asp.net  next?

**Comment by MicroPure** [comment]
似乎是停止更新了吧，难道不是吗

**Comment by ygorlazaro** [comment]
Well, I guess never. This project seems frozen. :(

**Comment by ynauls** [comment]
@sbohlen, is there a roap map for supporting ASP.NET 5? is this upgrade doable? There is 14K nuget downloads for the latest version of spring.core.  That still shows a strong community (maybe?) using spring.net.  What we are lacking is contributors, if we can breakdown the work involved in this upgrade I can def assist, and possibly @ynnuyonw  and @ygorlazaro can also :)

**Comment by ygorlazaro** [comment]
I'm in, for sure!

**Comment by gabrielsimas** [comment]
I´m in, too! Let´s begin!

**Comment by gabrielsimas** [comment]
The ASP.NET CORE 1 just released yet Release Candidate. but that does not stop to get something. The Spring.net can replace Autofac as dependency injection container, quietly

**Comment by Defee** [comment]
@gabrielsimas @ygorlazaro @ynauls The main problem for now is that spring.net doesn't support .netStandardLibraries. (or frameworks versions >=4,5). So solution libraries should be moved to .net core libraries. Some spring.net library dependencies haven't moved to .net core libraries yet. 

So if we want to help that framework, we should migrate/adopt Common.Logging library (Common.Logging.Core is migrated). Than we should migrate a Spring.Core dll, so we will have some base features support. I'm completely in to help that migration happen.

**Comment by gabrielsimas** [comment]
@Defee I´m in too! Let´s start!

**Comment by gabrielsimas** [comment]
@Defee And create Extension Method "UseSpring"... amazing!

**Comment by yahue** [comment]
amazing!

**Comment by lahma** [comment]
I've created a separate issue https://github.com/spring-projects/spring-net/issues/133 about general .NET Core support that tries to make progress and required steps more transparent.
