### ISSUE TITLE
Like operator and int64 not working together with HibernateTemplate

### ISSUE THREAD

**Issue by pastaav** [spring-projects/spring-net#126]
With an Oracle database table with a column named Data with type NUMBER(16,0) I could with old versions of Spring.Net and nHibernate write an HQL and use the like operator like done in regular SQL:

> string query =
>                     "from TD.Common.DataObject.TDDetectorFileInfo as info where info.Data like ?";
> object[] values1= new object[1];
> object[] values2 =new object[1];
> values1[0] = "19911111000000"
> values2[0] = "1991111100000%"
> var res = HibernateTemplate.Find<T>(query, values1);
> var res2 = HibernateTemplate.Find<T>(query, values2);

I expect to get the same result in res and res2 since the like operator in Oracle can be applied to numbers. 

Using Spring.Net 2.0.1 and NHibernate4 I instead get an expection for the res2 call.
Inner exception text: "Failed to convert parameter value from a String to a Decimal."

**Comment by gabrielsimas** [comment]
My friend. I don´t understand. Your field type on DB is NUMBER and you passes string on variables "values1" and "values2". have you tried using string cast to decimal?

**Comment by pastaav** [comment]
Thank you for the input. Unfortunately the LIKE operator without being able to use the wildcard character '%' is pretty much pointless. 

On the other hand further study of problem has made me suspect that the problem is not really located in Spring.Net. The NHibernate project has marked the API that uses the HQL syntax as deprecated. It seems likely NHibernates project has made the move to require typed parameters and the LIKE operator used in HQL suffer from this decision.

Currently I am considering to change API used for these calls. There is no strict requirement to stay with using the HQL syntax and I expect better performance if I avoid HQL.

**Comment by gabrielsimas** [comment]
Have you tried changing the HQL by Criteria or Linq to NHibernate?

**Comment by lahma** [comment]
I'm doing a rude experiment with closing this, like what stale bot does, but maybe more human as I will probably actually react to feedback. As this issue has been stale for so long, I'll close it. If it's still an issue you would like to pursue, we can definitely reopen. 

With limited resources this is just something that we need to do. Thank you for your understanding.
