### ISSUE TITLE
{"Error creating context 'spring.root': At least one object must implement IComparable."}

### ISSUE THREAD

**Issue by Imrahulk** [spring-projects/spring-net#128]
I am getting below error if i include two spring configuration xml file with PropertyPlaceholderConfigurer. This is happening after migrating from spring 2.0.1.40000 to 2.0.1.45000. I am trying to use it for WebApi 2

`<object type="Spring.Objects.Factory.Config.PropertyPlaceholderConfigurer, Spring.Core"> <property name="ConfigSections" value="databaseSettings"/> </object>
`
Stack Trace: 

[ArgumentException: At least one object must implement IComparable.]
   System.Collections.Comparer.Compare(Object a, Object b) +12063859
   System.Array.BinarySearch(Array array, Int32 index, Int32 length, Object value, IComparer comparer) +224

[InvalidOperationException: Failed to compare two elements in the array.]
   System.Array.BinarySearch(Array array, Int32 index, Int32 length, Object value, IComparer comparer) +308
   System.Collections.SortedList.IndexOfKey(Object key) +31
   System.Collections.SortedList.get_Item(Object key) +16
   Spring.Collections.DictionarySet.Add(Object element) in c:_prj\spring-net\src\Spring\Spring.Core\Collections\DictionarySet.cs:117
   Spring.Objects.Factory.Support.AbstractObjectFactory.AddEmbeddedValueResolver(IStringValueResolver valueResolver) in c:_prj\spring-net\src\Spring\Spring.Core\Objects\Factory\Support\AbstractObjectFactory.cs:2549
   Spring.Objects.Factory.Config.PropertyPlaceholderConfigurer.ProcessProperties(IConfigurableListableObjectFactory factory, NameValueCollection props) in c:_prj\spring-net\src\Spring\Spring.Core\Objects\Factory\Config\PropertyPlaceholderConfigurer.cs:267
   Spring.Objects.Factory.Config.PropertyResourceConfigurer.PostProcessObjectFactory(IConfigurableListableObjectFactory factory) in c:_prj\spring-net\src\Spring\Spring.Core\Objects\Factory\Config\PropertyResourceConfigurer.cs:245

[ObjectsException: Errored while postprocessing an object factory.]
   Spring.Objects.Factory.Config.PropertyResourceConfigurer.PostProcessObjectFactory(IConfigurableListableObjectFactory factory) in c:_prj\spring-net\src\Spring\Spring.Core\Objects\Factory\Config\PropertyResourceConfigurer.cs:255
   Spring.Context.Support.AbstractApplicationContext.InvokeObjectFactoryPostProcessors(IList objectFactoryPostProcessors, IConfigurableListableObjectFactory objectFactory) in c:_prj\spring-net\src\Spring\Spring.Core\Context\Support\AbstractApplicationContext.cs:664
   Spring.Context.Support.AbstractApplicationContext.InvokeObjectFactoryPostProcessors(IConfigurableListableObjectFactory objectFactory) in c:_prj\spring-net\src\Spring\Spring.Core\Context\Support\AbstractApplicationContext.cs:611
   Spring.Context.Support.AbstractApplicationContext.Refresh() in c:_prj\spring-net\src\Spring\Spring.Core\Context\Support\AbstractApplicationContext.cs:1014
   Spring.Context.Support.XmlApplicationContext..ctor(XmlApplicationContextArgs args) in c:_prj\spring-net\src\Spring\Spring.Core\Context\Support\XmlApplicationContext.cs:111
   Spring.Context.Support.XmlApplicationContext..ctor(String name, Boolean caseSensitive, String[] configurationLocations) in c:_prj\spring-net\src\Spring\Spring.Core\Context\Support\XmlApplicationContext.cs:156
   _dynamic_Spring.Context.Support.XmlApplicationContext..ctor(Object[] ) +167
   Spring.Reflection.Dynamic.SafeConstructor.Invoke(Object[] arguments) in c:_prj\spring-net\src\Spring\Spring.Core\Reflection\Dynamic\DynamicConstructor.cs:113
   Spring.Context.Support.RootContextInstantiator.InvokeContextConstructor(ConstructorInfo ctor) in c:_prj\spring-net\src\Spring\Spring.Core\Context\Support\ContextHandler.cs:562
   Spring.Context.Support.ContextInstantiator.InstantiateContext() in c:_prj\spring-net\src\Spring\Spring.Core\Context\Support\ContextHandler.cs:507
   Spring.Context.Support.ContextHandler.InstantiateContext(IApplicationContext parentContext, Object configContext, String contextName, Type contextType, Boolean caseSensitive, IList`1 resources) in c:_prj\spring-net\src\Spring\Spring.Core\Context\Support\ContextHandler.cs:343
   Spring.Context.Support.ContextHandler.Create(Object parent, Object configContext, XmlNode section) in c:_prj\spring-net\src\Spring\Spring.Core\Context\Support\ContextHandler.cs:288

[ConfigurationErrorsException: Error creating context 'spring.root': At least one object must implement IComparable.]
   System.Configuration.BaseConfigurationRecord.EvaluateOne(String[] keys, SectionInput input, Boolean isTrusted, FactoryRecord factoryRecord, SectionRecord sectionRecord, Object parentResult) +176
   System.Configuration.BaseConfigurationRecord.Evaluate(FactoryRecord factoryRecord, SectionRecord sectionRecord, Object parentResult, Boolean getLkg, Boolean getRuntimeObject, Object& result, Object& resultRuntimeObject) +1139
   System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject) +1612
   System.Configuration.BaseConfigurationRecord.GetSection(String configKey) +41
   System.Web.HttpContext.GetSection(String sectionName) +52
   System.Web.Configuration.HttpConfigurationSystem.GetSection(String sectionName) +56
   System.Web.Configuration.HttpConfigurationSystem.System.Configuration.Internal.IInternalConfigSystem.GetSection(String configKey) +11
   System.Configuration.ConfigurationManager.GetSection(String sectionName) +79
   Spring.Util.ConfigurationUtils.GetSection(String sectionName) in c:_prj\spring-net\src\Spring\Spring.Core\Util\ConfigurationUtils.cs:68
   Spring.Context.Support.ContextRegistry.InitializeContextIfNeeded() in c:_prj\spring-net\src\Spring\Spring.Core\Context\Support\ContextRegistry.cs:388
   Spring.Context.Support.ContextRegistry.GetContext() in c:_prj\spring-net\src\Spring\Spring.Core\Context\Support\ContextRegistry.cs:252
   Spring.Web.Mvc.SpringMvcApplication.BuildDependencyResolver() in c:_prj\spring-net\src\Spring\Spring.Web.Mvc4\SpringMvcApplication.cs:69
   Spring.Web.Mvc.SpringMvcApplication.Application_BeginRequest(Object sender, EventArgs e) in c:_prj\spring-net\src\Spring\Spring.Web.Mvc4\SpringMvcApplication.cs:53
   System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +141
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +69

**Comment by marcellalves** [comment]
Have you solved this issue? I'm with the same problem here.

**Comment by lahma** [comment]
I'm doing a rude experiment with closing this, like what stale bot does, but maybe more human as I will probably actually react to feedback. As this issue has been stale for so long, I'll close it. If it's still an issue you would like to pursue, we can definitely reopen. 

With limited resources this is just something that we need to do. Thank you for your understanding.
