### ISSUE TITLE
Some characters are not valid on expressions?

### ISSUE THREAD

**Issue by jacargentina** [spring-projects/spring-net#130]
For example, trying to access a property named `AñosAntiguedad` on my c# class, i get an exception for unrecognized char 0x0F1.

If the response is a confirmation, it is possible to tweak the expression parser to allow me use those chars?

**Comment by lahma** [comment]
I'm doing a rude experiment with closing this, like what stale bot does, but maybe more human as I will probably actually react to feedback. As this issue has been stale for so long, I'll close it. If it's still an issue you would like to pursue, we can definitely reopen. 

With limited resources this is just something that we need to do. Thank you for your understanding.
