### ISSUE TITLE
.NET Core support

### ISSUE THREAD

**Issue by lahma** [spring-projects/spring-net#133]
This is an umbrella issue listing some things that need to be taken care of in order to get .NET Core support working.

- [x] make Common.Logging support .NET Core 
- [x] upgrade NUnit
- [x] replace Rhino.Mocks with FakeItEasy (in progress)
- [x] replace packages.config with project.json
- [x] replace project.json with new csproj
- [x] investigate [spring-net-futures fork](https://github.com/spring-net-futures/spring-net/tree/feature/netstandard-2.0) and bring in commits where appropriate

**Comment by gabrielsimas** [comment]
@lahma which branch?

**Comment by lahma** [comment]
Multiple branches, I'm currently working on getting NUnit 3.5 working, which is a prequisite on branch https://github.com/spring-projects/spring-net/tree/features/nunit35 , then I'll proceed with changing from Rhino.Mocks to FakeItEasy . These two then can go to master when working properly.

I guess initial project.json can go to master too if determined as functioning.

After that I can rebase branch https://github.com/spring-projects/spring-net/tree/features/netcore on top of master again. So easier changes first and building .NET in parallel. It's a big undertaking.

**Comment by gabrielsimas** [comment]
@lahma Thanks my friend.

**Comment by luizcarlosfaria** [comment]
Starting a few hours, i have some data to share and i think that can help on migrating Spring.NET to .NET Standard 2.0.

Isolating only Spring.Core i have great results on basic tests.

But i have issues to work on.

Default application context load, based on ConfigurationManager infrastructure are broken overall, but XmlApplicationContext still working fine on linux. The challenge today is adapt configuration models to run ubiquitous on windows and on linux.

To make a basic funcionality i have to replace things, using fake implementations about:
Common.Logging
System.Runtime.Remoting.Messaging.CallContext (replaced with ConcurrentDictionary<string, AsyncLocal<object>>)
System.Runtime.Remoting.RemotingServices (replaced with fake implementation)
System.Runtime.Remoting.RealProxy(replaced with fake implementation)
System.Runtime.Remoting.IRemotingTypeInfo(replaced with fake implementation)

Later, this week i'll share the project. It's not a fork, is a sugar to explain that is possible, and we are near to solve that. We are going to .NET Core! It's awesome!

**Comment by lahma** [comment]
Following projects now compile under netstandard2.0:

* Spring.Aop
* Spring.Core
* Spring.Data
* Spring.Messaging
* Spring.Testing.NUnit

Basically things not supported in netstandard/.NET Core have been left out of compilation (remoting, enterprise services etc).

Closing this as the main steps have been completed. There probably are more improvements that can be made as separate issues.

**Comment by Salgat** [comment]
@lahma Any plans on when Spring.Core (netstandard version) will be pushed to nuget, even as a prerelease?
