### ISSUE TITLE
JSON Support for IMessageConverter (Spring.Messaging.Nms.Support.Converter)

### ISSUE THREAD

**Issue by irperez** [spring-projects/spring-net#137]
I'm new to spring so forgive me for my ignorance.

I would like to suggest adding a JSON MessageConverter to the Spring.Messaging.Nms.Support.Converter namespace.

I can easily do this and base it on the JSON.Net or some other JSON serializer that this group prefers.  Or possibly make the JSON serializer configurable some how.

The payload size is so much smaller than XML hence better performance over the wire.  I'm going to implement this for my company regardless.  But looking to contribute for the greater good.

What is everyone's thoughts?  Maybe this was already suggested?

**Comment by irperez** [comment]
I have a working sample that I've tested out, based on Json.Net.  I'm sure another serializer could work if needed.  Or as I said, I can make it configurable.  Any thoughts?

[Here is a the code (gist)](https://gist.github.com/irperez/2cc61c8ca18790340f92cd2911500a03)

**Comment by lahma** [comment]
I'm doing a rude experiment with closing this, like what stale bot does, but maybe more human as I will probably actually react to feedback. As this issue has been stale for so long, I'll close it. If it's still an issue you would like to pursue, we can definitely reopen. 

With limited resources this is just something that we need to do. Thank you for your understanding.
