### ISSUE TITLE
Make SyntaxErrorException public

### ISSUE THREAD

**Issue by jacargentina** [spring-projects/spring-net#138]
Would be nice to have the pure exception available to catch it and point the user the UI editor position where the problem is. There is a `column` property that would help a lot for doing that.

My only option now it to parse the message from the exception as i cant directly catch it, being it `internal`

**Comment by lahma** [comment]
I'm doing a rude experiment with closing this, like what stale bot does, but maybe more human as I will probably actually react to feedback. As this issue has been stale for so long, I'll close it. If it's still an issue you would like to pursue, we can definitely reopen. 

With limited resources this is just something that we need to do. Thank you for your understanding.
