### ISSUE TITLE
Tenant per request

### ISSUE THREAD

**Issue by jdnichollsc** [spring-projects/spring-net#139]
Hi guys,

Is possible to instance a Data context of **Entity Framework** per request with a different **connection string**?

I'm using the following object to configure **Sprint**:
```xml
<objects xmlns="http://www.springframework.net">
  <description>My business services</description>
  <object id="DataContext" type="MyProject.Persistence.DataContext, MyProject" scope="request">
</objects>
```

Thanks in advance, Nicholls

**Comment by lahma** [comment]
I'm doing a rude experiment with closing this, like what stale bot does, but maybe more human as I will probably actually react to feedback. As this issue has been stale for so long, I'll close it. If it's still an issue you would like to pursue, we can definitely reopen. 

With limited resources this is just something that we need to do. Thank you for your understanding.
