### ISSUE TITLE
Is the project still alive?

### ISSUE THREAD

**Issue by neo-eureka** [spring-projects/spring-net#141]
Hello!
Is the project still alive and do you plan to develop it in the future?
The [website](http://www.springframework.net/) is dead since 2012, the latest announcement there is about 2.0.0 milestone, and it looks like it is still almost where it was more than 4 years ago. The [Code frequency](https://github.com/spring-projects/spring-net/graphs/code-frequency) is also a sorry sight.

**Comment by ojoadeolagabriel** [comment]
I am sure it is dead. Wondering why the. Net implementation is still a
concern to any right. Thinking engineer

**Comment by neo-eureka** [comment]
Maybe just because I have been programming in Java a lot...

**Comment by ojoadeolagabriel** [comment]
Yeah maybe,

Since i moved away from dot.net and its "zero community" "locked-down"
"cash for the simplest things" attitude. Things have never been this good.

Lol...

**Comment by lahma** [comment]
See https://github.com/spring-projects/spring-net/issues/187#issuecomment-891153665 .
