### ISSUE TITLE
Error creating context 'spring.root' inner exception: WebSupportModule not initialized

### ISSUE THREAD

**Issue by jorgemtnz** [spring-projects/spring-net#143]
I have an ASP.NET web application which compiles and uses some references, like Spring.Web, Spring.Core, Spring.Aop, Spring.Core and Spring.Services. The corresponding dlls are in the bin folder.
When I start the web application with Internet Explorer, I get this exception:Error creating context 'spring.root': An exception occurred in the type initializer of  
'Spring.Objects.Factory.Support.WebObjectFactory'. 
the inner exception TypeInitializationException: An exception occurred in the type initializer of 'Spring.Objects.Factory.Support.WebObjectFactory'. ConfigurationErrorsException: WebSupportModule not initialized. Did you forget to add <add name = "Spring" type = "Spring.Context.Support.WebSupportModule, Spring.Web" /> to your web.config's <httpModules> -section?

This is part of my webConfig
httpModules>
     add name="ScriptModule" type="System.Web.Handlers.ScriptModule, System.Web.Extensions, 
                   Version=3.5.0.0, Culture=neutral, PublicKeyToken=31BF3856AD364E35"/> 
      add name="Spring" type="Spring.Context.Support.WebSupportModule, Spring.Web"/> 
      add name="BRF" type="BRF.Core.Web.BRFHttpModule, BRF.Core.Web"/>
httpModules> 

But i do it right, so i do not understaing why happends the exception. What can i do?

**Comment by lahma** [comment]
I'm doing a rude experiment with closing this, like what stale bot does, but maybe more human as I will probably actually react to feedback. As this issue has been stale for so long, I'll close it. If it's still an issue you would like to pursue, we can definitely reopen. 

With limited resources this is just something that we need to do. Thank you for your understanding.
