### ISSUE TITLE
Spring.NET + NHibernate - Multiple (Distinct) Databases

### ISSUE THREAD

**Issue by robertovaldesperez** [spring-projects/spring-net#149]
Is it possible to configure two different databases with spring.net + nhibernate so that when the application is booted the tables are created in the different databases?

**Comment by lahma** [comment]
I'm doing a rude experiment with closing this, like what stale bot does, but maybe more human as I will probably actually react to feedback. As this issue has been stale for so long, I'll close it. If it's still an issue you would like to pursue, we can definitely reopen. 

With limited resources this is just something that we need to do. Thank you for your understanding.
