### ISSUE TITLE
How to create the file GenCommonAssemblyInfo.cs  ?

### ISSUE THREAD

**Issue by athinboy** [spring-projects/spring-net#158]
sorry, I don't know how to create the file GenCommonAssemblyInfo.cs .

  <ItemGroup>
    <Compile Include="..\GenCommonAssemblyInfo.cs">
      <Link>GenCommonAssemblyInfo.cs</Link>
      <SubType>Code</SubType>
    </Compile>
    <EmbeddedResource Include="Context\Config\spring-context-1.3.xsd" />
    <EmbeddedResource Include="Context\Config\spring-context-2.0.xsd" />
    <EmbeddedResource Include="Objects\Factory\Xml\spring-tool-1.1.xsd" />
    <EmbeddedResource Include="Objects\Factory\Xml\spring-objects-1.1.xsd" />
    <EmbeddedResource Include="Objects\Factory\Xml\spring-objects-1.3.xsd" />
    <EmbeddedResource Include="Objects\Factory\Xml\spring-objects-2.0.xsd" />
    <EmbeddedResource Include="Validation\Config\spring-validation-1.3.xsd" />
    <EmbeddedResource Include="Validation\Config\spring-validation-1.1.xsd" />
  </ItemGroup>

**Comment by lahma** [comment]
Run Build.cmd, it will generate in the beginning so you can stop the execution as soon as you see the file in your directory.

**Comment by athinboy** [comment]
@lahma 

Thanks!
but, still fail!
Sorry. I think we need a detail build document, thank for your help again!




NAnt 0.92 (Build 0.92.4543.0; release; 2012/6/9)
Copyright (C) 2001-2012 Gerry Shaw
http://nant.sourceforge.net

[loadtasks] Failure scanning "#############\spring-net\build-support\tools\nant\bin\NAnt.NUnit2Tasks.dll" for extensions. Could not load file or assembly “nunit.core.interfaces, Version=2.6.0.12051, Culture=neutral, PublicKeyToken=96d09a1eb7f44a77”or one of its dependencies. The system cannot find the file specified.
Buildfile: file:///##########/spring-net/Spring.build
Target framework: Microsoft .NET Framework 4.0
Target(s) specified: test 

[readregistry] Registry Path Not Found! - key='SOFTWARE\Microsoft\VisualStudio\9.0\';hive='LocalMachine';
     [echo] msbuild.exe:         'MsBuild.exe'
     [echo] global common-project.xml

check-package.passedbuildincrement:

  [sysinfo] Setting system information properties under sys.*
  [sysinfo] Property could not be created for environment variable 'ProgramFiles(x86)' : Property name 'sys.env.ProgramFiles(x86)' is invalid.
  [sysinfo] Property could not be created for environment variable 'CommonProgramFiles(x86)' : Property name 'sys.env.CommonProgramFiles(x86)' is invalid.

**Comment by lahma** [comment]
Does build stop here or is there more output? I don't see build phase triggering yet.

**Comment by athinboy** [comment]
>Build.cmd
AMD64 Processor Architecture Detected, setting up nant.exe.config for x64-based .NET reference paths.
已复制         1 个文件。
.
..
...
Running full Build Script, capturing output to buildlog.txt file...
Start Time: 16:58:48.58
.
..
...
Launching text file viewer to display buildlog.txt contents...
.
..
...
************************
Build Complete!
************************
End Time: 16:58:50.62

**Comment by athinboy** [comment]
![1](https://user-images.githubusercontent.com/10301079/46793278-e9ac8500-cd77-11e8-9434-36f1fdd9bd7b.JPG)

**Comment by lahma** [comment]
So what's the full contents of buildlog.txt? Was the following last line?

```
[sysinfo] Property could not be created for environment variable 'CommonProgramFiles(x86)' : Property name 'sys.env.CommonProgramFiles(x86)' is invalid.
```

**Comment by athinboy** [comment]
Wrong file?


![2](https://user-images.githubusercontent.com/10301079/46795583-11eab280-cd7d-11e8-9f94-b6362adb6679.JPG)

**Comment by athinboy** [comment]
[buildlog.txt](https://github.com/spring-projects/spring-net/files/2468357/buildlog.txt)

**Comment by athinboy** [comment]
Maybe Can not find  MsBuild.exe??

Spring.build(342,4):
'MsBuild.exe' failed to start.
    The system cannot find the file specified.

**Comment by athinboy** [comment]
After I add the ‘C:\Program Files (x86)\MSBuild\14.0\Bin’ to  the environment variable path,
I get another message:
 
     [exec] F:\fenggq\study\github\spring-net\Spring.Net.sln.metaproj : The target "Restore" does not exist in the project. (MSB4057)”。 [F:\fenggq\study\github\spring-net\Spring.Net.sln]



[buildlog.txt](https://github.com/spring-projects/spring-net/files/2468509/buildlog.txt)

**Comment by lahma** [comment]
Do you have Visual Studio 2017 installed? Community edition should be fine.

**Comment by athinboy** [comment]
Yes，I installed VS2017 Community  edition.  I am confused about build   , i have  not used  NAnt.  
Thanks for your help!

**Comment by athinboy** [comment]
After I change Msbuild.exe path to Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin , It work.
Through  I install vs2017 in D: rather then C: (   Spring.include  line 23~33) .

**Comment by athinboy** [comment]
https://developercommunity.visualstudio.com/content/problem/357783/how-to-find-vs2017-installation-directory-in-reged.html

https://github.com/Microsoft/vswhere
