### ISSUE TITLE
Improve performance

### ISSUE THREAD

**Issue by lahma** [spring-projects/spring-net#164]
As it's now the hip thing to do in .NET land, let's try to improve speed and reduce memory allocations. This is an umbrella issue to track changes. 

Reflecting against https://github.com/danielpalme/IocPerformance .

Starting point:

``` ini

BenchmarkDotNet=v0.11.1, OS=Windows 10.0.17763
AMD Ryzen 7 2700X Eight-Core Processor (Max: 4.10GHz), 1 CPU, 16 logical and 8 physical cores
.NET Core SDK=2.1.403
  [Host] : .NET Core 2.1.5 (CoreCLR 4.6.26919.02, CoreFX 4.6.26919.02), 64bit RyuJIT
  Clr    : .NET Framework 4.7.2 (CLR 4.0.30319.42000), 64bit RyuJIT-v4.7.3190.0
  Core   : .NET Core 2.1.5 (CoreCLR 4.6.26919.02, CoreFX 4.6.26919.02), 64bit RyuJIT


```
|           Method |  Job | Runtime | Iterations |      Mean |     Error |    StdDev |      Gen 0 |   Allocated |
|----------------- |----- |-------- |----------- |----------:|----------:|----------:|-----------:|------------:|
| ResolveTransient |  Clr |     Clr |       5000 | 81.763 ms | 0.1666 ms | 0.1558 ms | 57857.1429 | 44462.74 KB |
| ResolveSingleton |  Clr |     Clr |       5000 |  6.559 ms | 0.0846 ms | 0.0791 ms |   453.1250 |   351.96 KB |
| ResolveTransient | Core |    Core |       5000 | 74.971 ms | 0.3587 ms | 0.3356 ms | 57857.1429 | 44457.56 KB |
| ResolveSingleton | Core |    Core |       5000 |  7.000 ms | 0.0982 ms | 0.0919 ms |   453.1250 |   351.91 KB |

**Comment by lahma** [comment]
After #161 was merged.

``` ini

BenchmarkDotNet=v0.11.1, OS=Windows 10.0.17763
AMD Ryzen 7 2700X Eight-Core Processor (Max: 4.00GHz), 1 CPU, 16 logical and 8 physical cores
.NET Core SDK=2.1.403
  [Host] : .NET Core 2.1.5 (CoreCLR 4.6.26919.02, CoreFX 4.6.26919.02), 64bit RyuJIT
  Clr    : .NET Framework 4.7.2 (CLR 4.0.30319.42000), 64bit RyuJIT-v4.7.3190.0
  Core   : .NET Core 2.1.5 (CoreCLR 4.6.26919.02, CoreFX 4.6.26919.02), 64bit RyuJIT


```
|           Method |  Job | Runtime | Iterations |      Mean |     Error |    StdDev |      Gen 0 |  Allocated |
|----------------- |----- |-------- |----------- |----------:|----------:|----------:|-----------:|-----------:|
| ResolveTransient |  Clr |     Clr |       5000 | 38.127 ms | 0.1220 ms | 0.1141 ms | 11857.1429 | 9150.55 KB |
| ResolveSingleton |  Clr |     Clr |       5000 |  4.354 ms | 0.0085 ms | 0.0071 ms |   453.1250 |  351.96 KB |
| ResolveTransient | Core |    Core |       5000 | 38.484 ms | 0.0832 ms | 0.0695 ms | 11857.1429 | 9149.57 KB |
| ResolveSingleton | Core |    Core |       5000 |  4.574 ms | 0.0122 ms | 0.0114 ms |   453.1250 |  351.91 KB |

**Comment by lahma** [comment]
After #165 was merged.


``` ini

BenchmarkDotNet=v0.11.1, OS=Windows 10.0.17763
AMD Ryzen 7 2700X Eight-Core Processor (Max: 4.00GHz), 1 CPU, 16 logical and 8 physical cores
.NET Core SDK=2.1.403
  [Host] : .NET Core 2.1.5 (CoreCLR 4.6.26919.02, CoreFX 4.6.26919.02), 64bit RyuJIT
  Clr    : .NET Framework 4.7.2 (CLR 4.0.30319.42000), 64bit RyuJIT-v4.7.3190.0
  Core   : .NET Core 2.1.5 (CoreCLR 4.6.26919.02, CoreFX 4.6.26919.02), 64bit RyuJIT


```
|           Method |  Job | Runtime | Iterations |      Mean |     Error |    StdDev |     Gen 0 |  Allocated |
|----------------- |----- |-------- |----------- |----------:|----------:|----------:|----------:|-----------:|
| ResolveTransient |  Clr |     Clr |       5000 | 26.579 ms | 0.1103 ms | 0.1032 ms | 1968.7500 |  1525.1 KB |
| ResolveSingleton |  Clr |     Clr |       5000 |  4.624 ms | 0.0279 ms | 0.0261 ms |  453.1250 |  351.96 KB |
| ResolveTransient | Core |    Core |       5000 | 25.780 ms | 0.1411 ms | 0.1320 ms | 1968.7500 | 1524.94 KB |
| ResolveSingleton | Core |    Core |       5000 |  4.404 ms | 0.0718 ms | 0.0600 ms |  453.1250 |  351.91 KB |

**Comment by jeffreyschultz** [comment]
How can we reproduce your results? I know that I was seeing quite poor performance when I migrated the framework to .Net Standard 2.0. It was one of the unit tests where it iterates somewhere around 20000 times. The original code would go through this pretty quickly, but the migrated code ran VERY slowly through this unit test.

**Comment by lahma** [comment]
@jeffreyschultz humm, didn't notice such big difference, but anyway you should be able to run tests by:

```
cd .\test\Spring\Spring.Benchmark
dotnet build -c Release
dotnet run -c Release --framework netcoreapp2.1
```

Then select `0` for container tests.

**Comment by lahma** [comment]
Next to investigate is how to make CodeConfig faster, it suffers in container startup time which is also tested in the https://github.com/danielpalme/IocPerformance benchmark.

**Comment by lahma** [comment]
More specific issues can be opened when needed.
