### ISSUE TITLE
Searching for old WPF Support

### ISSUE THREAD

**Issue by Simulacrux** [spring-projects/spring-net#166]
Hello,

I'm currently trying to port some of my older WinForms UIs to WPF and for the whole backend DI there is Spring.Net used. Now I discovered that it is not as easy to get the MVVM Pattern up and running around the Spring container. If it were for new projects, I would switch to Catel or Caliburn.Micro for that problems, but we are using Spring.Net for AOP stuff in this application and so I want to stick to one Framework.
I read from a experimental WPF integration for XAML Views and stuff in your old forum. But I did not manage to get a hold on the sources for that implementation. Is there a way to recover the old stuff done back there. It seems to be working quite well for simple Views and would be a nice Addin in the Spring Framework. Maybe it could be stored in a separate GitHub repository for interested people to commit to it.

Cheers
Simulacrux

**Comment by lahma** [comment]
I'm doing a rude experiment with closing this, like what stale bot does, but maybe more human as I will probably actually react to feedback. As this issue has been stale for so long, I'll close it. If it's still an issue you would like to pursue, we can definitely reopen. 

With limited resources this is just something that we need to do. Thank you for your understanding.
