### ISSUE TITLE
Enable preview builds

### ISSUE THREAD

**Issue by lahma** [spring-projects/spring-net#167]
We currently have Appveyor builds running. Now that there's .NET Core support in master it would be lovely to have some kind of preview builds. Microsoft has opened free Azure DevOpsCiWhatNot for OSS projects that could also handle thins.

I'm pinging @sbohlen to get some feedback. You've set the current system, who should proceed? I've set a MyGet feed ( https://www.myget.org/feed/Packages/springnet ) that could be used and I'm gladly giving you maintainer permissions if you want. I've been a little lonesome cowboy here doing the changes so all help if time permits is always welcome.

**Comment by freemansoft** [comment]
Are you talking about this Azure feature/announcement https://azure.microsoft.com/en-us/blog/announcing-azure-pipelines-with-unlimited-ci-cd-minutes-for-open-source/

**Comment by lahma** [comment]
@freemansoft yep, that's the thing if it's feasible. I guess they don't have good database integration testing story yet though.

**Comment by sbohlen** [comment]
@lahma I'm not at all married to Appveyor per se.  But that said, I also don't have any *issue* with them either.  Is there a compelling advantage to shifting to the Azure DevOps pipeline for OSS instead of Appveyor?

**Comment by lahma** [comment]
@sbohlen The Azure DevOps was more idea to throw as an alternative or even to run on both. I don't see any reason to change for the sake of a change, Appveyor works like a charm and you did wonderful job getting it to run integration tests too - which I believe is quite hard to achieve at the moment in DevOps land.

If you happen to have the time to check what configuration would be needed for Appveyor to push the MyGet feed I would appreciate that. As you are the admin of the Appveyor project, only you can create the secrets needed. See Quartz.NET's definition [here](https://github.com/quartznet/quartznet/blob/master/appveyor.yml). I you would like to, I can set you as an admin for the MyGet feed, just send me your MyGet username or e-mail address you would like to use as private message (email, GitHub, tweet, whatever works).

Then the required thing would be the deploy addition to appveyor.yml with your encrypted secret, like decribed in the [docs](https://www.appveyor.com/docs/deployment/nuget/).

**Comment by rmszc81** [comment]
Is there any 2.0.1 package after fix no #120 ?
I had no success trying to build the source code by myself. Would you kindly guys help on it?
* it must be this version, due to other dependencies on a legacy project.
thanks!

**Comment by Ablu** [comment]
Is there anything that can be done to assist this?

**Comment by rmszc81** [comment]
@ablu, no.

This issue was for a company project that I was working before, now it doesn't matter anymore.

I solved by cloning the repository and building the binaries through vs2010. Then I added the references to the project manually. Problem was solved and case closed 

Thanks for the support anyway.

Regards,

[],

@rmszc81

**Comment by Ablu** [comment]
I meant the general task of providing preview builds :)

But I am glad that you were able to resolve your issue.
