### ISSUE TITLE
Database configuration for running Spring.Data tests?

### ISSUE THREAD

**Issue by freemansoft** [spring-projects/spring-net#168]
What type of database and configuration are expected when Spring.Data tests?
<edit>
I did find this ODBC connection string in app.config
value="dsn=MyDSN;uid=sa;pwd=myPassword;"
</edit>

**Comment by lahma** [comment]
You can check how AppVeyor build sets the database, the scripts can be found here: https://github.com/spring-projects/spring-net/tree/master/build-support . The files with `appveyor- `prefix.

You need to create db with schema and users and then create alias that is recognized.

I think this is a bit too complicated as it tries to overcome problems with different SQL Server setups that nowadays could be circumvented by using a Dockerized version running on specific port. This setup could be shared via Docker Compose for easier setup.
