### ISSUE TITLE
ASP.NET Core integration

### ISSUE THREAD

**Issue by mashbrno** [spring-projects/spring-net#173]
Maybe a silly question, but we're trying to build up a new frontend on business logic build on Spring.Net. Is there any info about integration with asp.net core build in IoC?

**Comment by Igneous01** [comment]
I don't think they are compatible, as .NET core has it's own primitive IoC in the startup.cs that configures everything in your solution. You wouldn't be able to use Spring IoC to inject dependencies into controllers for example.

**Comment by akunzai** [comment]
I have created a tiny library to integrate Spring.NET with Microsoft.Extensions.DependencyInjection

- [Spring.Extensions.DependencyInjection](https://www.nuget.org/packages/Spring.Extensions.DependencyInjection/)

maybe it can helps,

please give it a try, any feedback/PR is welcome.

**Comment by mashbrno** [comment]
Thanks @akunzai I will give a try. Currently I have successfully included [FluentContext](https://github.com/suremaker/Spring.FluentContext/), will try to combine them. I would like to see these features as core parts of *Spring.Net*. It will make the framework aligned with order IoCs.
