### ISSUE TITLE
Should I still use this?

### ISSUE THREAD

**Issue by JstrzAtW2M** [spring-projects/spring-net#186]
Seems like it may still be active, but not really sure. We're looking to start using a nice app framework. Does this have a future?

**Comment by ADGrant** [comment]
Looks pretty dead to me. I am thinking about moving an old legacy project off of Spring.

**Comment by Exagram** [comment]
Is there a contact of someone that can accept PR's?

**Comment by lahma** [comment]
PRs are welcome and appreciated, see https://github.com/spring-projects/spring-net/issues/187#issuecomment-891153665
