### ISSUE TITLE
.NET standard release plan

### ISSUE THREAD

**Issue by cezarypiatekGC** [spring-projects/spring-net#187]
Hi

I'm considering using `Spring.Messaging.Nms` in several projects for my company. The main obstacle that prevents me from taking it right now is the lack of the release of a version compatible with the .NET standard. I would like to know what is the current status of porting `Spring.Messaging.Nms` to .net standard and what are the release plans?

**Comment by mashbrno** [comment]
Would be great if you can create at least pre-release NuGet packages. I had to create my own [Nugets](https://www.nuget.org/packages/D3S.Spring.Core/3.0.0-pre) to use in my own projects, but that is not generally good idea as other people don't know what to expect from such forks

**Comment by lahma** [comment]
I just pushed changes to master and `Spring.Messaging.Nms` now has netstandard2.0 target, can't promise a NuGet release or a date though.

**Comment by lwqwag** [comment]
Will next release be based on .netcore2.2 or .netcore3.0?

**Comment by lahma** [comment]
It's netstandard 2.0 so works on both.

**Comment by lwqwag** [comment]
Thanks for your reply

**Comment by Simulacrux** [comment]
Hi everyone,

as my fellow pre-poster wrote and also was stated in issue #167 , it would be very helpful to have  official pre-release Nugets of the new Spring.Net version. Not everyone is able to compile and sign it on his own and if I understand the Milestones correct, the only open issue right now is the performance improvement. For my part, this would be a nice to have, but getting a new version (pre-release) of Spring.Net out in the world would be a nice Christmas  gift. 

Cheers
Simulacruxx

**Comment by michaelandrepearce** [comment]
@lahma any update here with release?

**Comment by lahma** [comment]
Sorry for the radio silence. Currently I have little to give as I don't have permissions to the official NuGet feed. Best what I could do is to try to get some myget/GitHub feed up. The performance testing branch is not essential for the release. I believe that the version as-is with the .NET Core support is better than nothing, hopefully at least.

**Comment by gergroen** [comment]
A release would be great. @lahma Do you know who has the permissions for the official nuget feed?

**Comment by lahma** [comment]
Based on [the core package NuGet page](https://www.nuget.org/packages/Spring.Core/)  @markpollack and @sbohlen have the keys to the kingdom 🙂

**Comment by Simulacrux** [comment]
Yes from my point of view, every possible (pre-)release would be great. 

As I'm hosting my own Nuget gallery at work for our inhouse project releases, I would be quite happy with just getting a "Zip" release to Github with the .nupkg and/or DLLs in there. Or some similar way of obtaining the latest bits. 

Of yourse we should try to figure out the kingdom keys, but for the short term I would be quite happy with any "workaround" release.

THX @lahma for your continuous work for Spring.Net

**Comment by michaelandrepearce** [comment]
+1 agreed, at least a release in github would be good, so people could consume a binary nuget pkg release, and then if/when nuget.org perms are sorted the packages could always be posthumously uploaded to nuget.

**Comment by agudets** [comment]
Are there any chances to have at least pre-release .net standard version in short term (1-2months)?

**Comment by mashbrno** [comment]
It's a bit off topic, but from my point of view - Spring is not ready for .NET Core. I spend some time trying to make it work as our code base is tightly coupled with Spring.NET. But there are many unresolved issues, which need considerable amount of time to fix:

- there's no integration with ASP.NET Core
- Common.Logging is not compatible with `Microsoft.Extensions.Logging`
- `async/await` support for `Spring.Data` transactions
- lack of EF Core support

We still have no successor for Spring's superb *expressions* and *validations*.

**Comment by lahma** [comment]
> * there's no integration with ASP.NET Core

Probably doable, but require a champion to create a PR.

> * Common.Logging is not compatible with `Microsoft.Extensions.Logging`

Microsoft's version has won the battle so I think it would make sense to switch over to that.

> * `async/await` support for `Spring.Data` transactions

Just overloads needed?

> * lack of EF Core support

I think EF isn't supported either. What would this include?

**Comment by mashbrno** [comment]
`async/await` - there's more about NHibernate session thread safety. For sure it will end up as an overload, but quite complex one.

EF is also not supported, but it's getting mature and competitive with NHibernate. It's now suitable for wider range of projects than in 2005. Eg. NHibernate.Spatial.MsSql was full .NET for very long time (due to reference to `Microsoft.SqlServer.Types`).

**Comment by terrajobst** [comment]
@lahma

We just had a customer asking us about spring.net and whether it will support .NET Standard/.NET Core. You mentioned earlier that you can't promise a package. Is there anything we could help you with you?

**Comment by lahma** [comment]
I have pinged @sbohlen about modifying the NuGet org permissions. I think I'll also have a go to get GitHub actions working to release to NuGet package repository in the near future.

**Comment by jgermanos** [comment]
> I have pinged @sbohlen about modifying the NuGet org permissions. I think I'll also have a go to get GitHub actions working to release to NuGet package repository in the near future.
@lahma any ETA on the release to NuGet?  thanks.

**Comment by maulik-modi** [comment]
@markpollack, @sbohlen and @lahma , Is there anything we could help you with? 
@terrajobst  is also interested

**Comment by maulik-modi** [comment]
I can see that https://www.nuget.org/packages/castle.core/ is being used by Popular libraries such as EFCore, FakeItEasy etc... to provide dynamic proxy

**Comment by Simulacrux** [comment]
Hi everyone,

yes I would also available to help with a release. Did not do any Github actions until now, but did a lot of other Build processes before, so should be manageable/learnable.
I checked the other Pre-Upload in the Nuget gallery and this packages are without strong named DLLs, because at this time the signing key was not available. Therefore I downloaded the current sources and did a local build with signing and packing in Nugets. It is not tested for now from my side, but I thought I just share it here, so maybe some other could also have a look onto it.
Version is 3.0.0 and Alpha1 as Prerelease signature.

Happy Testing
Simulacrux
[Spring.Nuget.3.0.0-Alpha1.zip](https://github.com/spring-projects/spring-net/files/6368213/Spring.Nuget.3.0.0-Alpha1.zip)

**Comment by lahma** [comment]
On top of earlier progress:

* I have now reworked the build pipeline to use NUKE build and it now builds and tests on both Windows and Linux.
* I decided to push the 3.0.0 release to NuGet, now there's something to use at least, there may be dragons - but the original idea was to have reworked, netstandard-compatible mostly backwards compatible version out

I have spent considerable amount of my time (including part of my recent summer holiday) to get things working on .NET Core / NET5, all the permissions and setups done (collaboration with past maintainers), fighting the build system etc.  Please do not expect me start fixing everything you might find, but provide pull requests to push things forward. Now publishing new versions should at least be (a lot) simpler.

There's always [option to sponsor](https://github.com/sponsors/lahma), if you want to show gratitude of the past work, this will not bind me to future work 😉 

Let's consider this issue fixed!
