### ISSUE TITLE
Net Core Sytem.Runtime.Remoting

### ISSUE THREAD

**Issue by aexhg** [spring-projects/spring-net#198]
https://github.com/spring-projects/spring-net/blob/master/src/Spring/Spring.Core/Expressions/PropertyOrFieldNode.cs#L28

Is this supposed to work on Net Core 3/5? According to this https://docs.microsoft.com/en-us/dotnet/core/porting/net-framework-tech-unavailable is unavailable and it doesn't seem to work if you have an expression that tries to set member values such as
```
Expression.Parse("(#x=MyClass(); #x.Value=3)");
```
you get a runtime error along lines of cannot find assembly System.Runtime.Remoting error from 
https://github.com/spring-projects/spring-net/blob/master/src/Spring/Spring.Core/Expressions/PropertyOrFieldNode.cs#L360

**Comment by lahma** [comment]
The call to `IsTransparentProxyshould` should actually hit here with netstandard build:

https://github.com/spring-projects/spring-net/blob/1054af4504ea1184d99dece8f355b4ad39ba406f/src/Spring/Spring.Core/Util/Shims.cs#L3-L9

There's no hard reference to Remoting in core that I can see in master.

**Comment by aexhg** [comment]
Thanks. Look forward to v3
