### ISSUE TITLE
Unable to run all tests from Spring.Core.Tests

### ISSUE THREAD

**Issue by asvaghela** [spring-projects/spring-net#206]
I am trying to run tests from Spring.Core.Tests but somehow it failed. 

Do I have missed any project configuration ?

My build was successfully.

![build](https://user-images.githubusercontent.com/49635116/126274752-aa1c1d7b-cf83-41f7-8f64-3f2913183c0f.png)

Out of 2488 tests from Spring.Core.Tests
Successful tests : 2038
Failed tests : 417
Skiped tests : 19
Not Run : 14

![tests](https://user-images.githubusercontent.com/49635116/126275141-6042a6a5-5f1b-48e1-b03c-b3271cad232e.png)

**Comment by asvaghela** [comment]
Recently I forked Spring.net v3.0 GA and started to run test cases. few of them of Spring.Core tests are failed.

**For .NET 5.0**

![image](https://user-images.githubusercontent.com/49635116/130585612-46986800-370d-4bb7-988c-ad45d9f3a42b.png)

**For .NET 4.6.1**

![image](https://user-images.githubusercontent.com/49635116/130585770-6fcf607d-7ae4-44db-8307-1e64f9de44be.png)

**Comment by lahma** [comment]
Tests were improved a while ago, I'm closing this for now and we can reopen if there still are specific problems.
