### ISSUE TITLE
Spring.Data.NHibernate5 not including in NuGet 

### ISSUE THREAD

**Issue by rguerrero** [spring-projects/spring-net#208]
I can't see Spring.Data.NHibernate5 in Nuget:

<img width="1120" alt="Captura de Pantalla 2021-08-02 a la(s) 12 49 06" src="https://user-images.githubusercontent.com/225333/127896365-556b0aac-8f2c-4fc9-9ba8-5ec85bd78680.png">

**Comment by lahma** [comment]
Yes the automatic publish couldn't push as it wasn't existing package, I'll have to push manually after I gest permissions sorted, I'll update here when available.

**Comment by rguerrero** [comment]
thanks @lahma !!

**Comment by lahma** [comment]
NuGet team had reserved the Spring* prefix and the ownership has been transferred and a re-run published also the missing packages. Thanks for reporting this!
