### ISSUE TITLE
Unable to restore Test project Nuget packages Spring.NET 3.0 GA.

### ISSUE THREAD

**Issue by asvaghela** [spring-projects/spring-net#211]
I just pull the latest from Spring.NET 3.0. I successfully restore package for CORE spring projects but I unable to restore package of all Tests projects. I am using VS 2019.

![image](https://user-images.githubusercontent.com/49635116/130507009-f920b8ec-d46e-480d-9668-7a1f4c3e3538.png)
![image](https://user-images.githubusercontent.com/49635116/130507150-b5218be6-ff08-4e81-a012-c7ed7a02612d.png)

**Comment by lahma** [comment]
Does running build.cmd fail too? Weird error as everything is green in CI.

**Comment by asvaghela** [comment]
build.cmd runs fine and weired error gone after  restart visual studio.
