### ISSUE TITLE
Spring.Core A strongly-named assembly is required.

### ISSUE THREAD

**Issue by Tricinty** [spring-projects/spring-net#212]
Hi,
After updating the Spring.Core from version 2.0.1 to the latest version 3.0.0. When I try to start my project I get this exception:
System.IO.FileLoadException: 'Could not load file or assembly 'Spring.Core, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)'

Target plattform: .Net Framework 4.7.1

Can anyone help with this?

Sincerely

**Comment by mrsegen** [comment]
Without knowing more about how your solution is set up, below are some things that have helped us in similar situations. (Admittedly, we haven't tried upgrading our app from 2 to 3 yet.)
* Check config file(s) that list `dependentAssembly`s for any that weren't auto-updated. (In our set up, sometimes, we have to make manual changes to our `*.config` file. Maybe try searching the solution for 'Spring.Core' to find a spot where `2.0.1.0` hasn't been replaced with `3.0.0.0`.)
* Try Rebuilding? (Clean + Build)
* Try unloading the project(s) then reloading with dependencies? (Can be done via right click in Solution Explorer)

Thanks for posting so as to give others preparing for this update a sneak peek!

**Comment by kales5** [comment]
I created a pull request to fix this issue: https://github.com/spring-projects/spring-net/pull/229
as we have the same issue in our project.

**Comment by lahma** [comment]
Change has been merged.

**Comment by lahma** [comment]
This should now be available on NuGet as version 3.0.1
