### ISSUE TITLE
WebObjectFactory has incomplete disposable support for request and session

### ISSUE THREAD

**Issue by cherrydev** [spring-projects/spring-net#46]
WebObjectFactory has the following implementation (OnEndSession is similar):

``` C#
        /// <summary>
        /// Disposes all 'request'-scoped objects at the end of each Request
        /// </summary>
        private static void OnEndRequest(HttpContext context)
        {
            IDictionary items = context.Items[OBJECTTABLEKEY] as IDictionary;

            if (items != null)
            {
                log.Debug("disposing 'request'-scoped item cache");
                ArrayList keys = new ArrayList(items.Keys);
                for (int i = 0; i < keys.Count; i++)
                {
                    IDisposable d = items[keys[i]] as IDisposable;
                    if (d != null)
                    {
                        d.Dispose();
                    }
                }
            }
        }
```

AbstractObjectFactory has no explicit ([but broken, actually](https://github.com/SpringSource/spring-net/issues/45)) support for separate scopes for disposable objects but for non scoped singletons, it has a fairly complex procedure of checking the objects up front for IDisposable interface, or an on-destroy definition (and wrapping that in an IDisposable), registering them, calling Dispose() on them when necessary, and also calling any DestructionAwareBeanPostProcessors.  Therefore, scoped singleton support for IDisposable in WebObjectFactory is currently incomplete since it does not support on-destroy configuration, DestructionAwareBeanPostProcessors or dependent objects.  I'll also note that the calls to Dispose() are unsafe since they are not wrapped in try blocks.

Please note that currently, ALL scoped singleton support for IDisposable is broken, so it will be necessary to fix this after, or in tandem with, the other [issue](https://github.com/SpringSource/spring-net/issues/45).

**Comment by lahma** [comment]
I'm doing a rude experiment with closing this, like what stale bot does, but maybe more human as I will probably actually react to feedback. As this issue has been stale for so long, I'll close it. If it's still an issue you would like to pursue, we can definitely reopen. 

With limited resources this is just something that we need to do. Thank you for your understanding.
