### ISSUE TITLE
Type Casting at Runtime for Array.SetValue

### ISSUE THREAD

**Issue by dsscsystems** [spring-projects/spring-net#59]
![bugs_spring_expressionevaluate_01](https://f.cloud.github.com/assets/5005685/1806386/8171a6da-6cad-11e3-906d-f6b3cbd19238.png)
Hello,

I am having a problem with an expression, not sure if it is becus of what i am doing or a bug. Here the expression (see below). What it is doing is this, i load and instance of a class and call one of it properties called "Steps" which contains a string value of float values like so "1,4,3,0,5,6,2,8,0".

I then pass Steps as a parameter to a static method call Conv.ToFloatArray(string) which returns an array of float[] value which is then used as a parameter for the next static that is called Algbra.StDev(float[]) this function returns a float value based on the value that is return the expression should return true or false. But instead throws an error, the exception is being thrown in this method: Spring.Util.ReflectionUtils.PackageParamArray(object[] argValues, int argCount, Type elementType).

It seems that when before it calls my Algbra.StDev(float[]) method, it tries to package the array of float and it fails and throws an error.I have added the logic for the methods i am using hopefully u will be able to help me resolve this and or maybe a work around.

Expression:
(Algbra.StDev(Conv.ToFloatArray(Steps, ',', 3)) > 3.5)

Values:
GblStats.Steps = "1,4,3,0,5,6,2,8,0";

Instance:
public class GblStats
{
[System.ComponentModel.DataObjectField(false, false, false)]
        [System.ComponentModel.Browsable(true)]  
        public string Steps
        {
            [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
            get { return m_steps; }
            [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
            set
            {
                if (m_steps != value)
                {
                    m_steps = value;
                    PropertyHasChanged();
                }
            }
        }
}

public static class Conversion
    {
[System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.NoInlining,
            MethodCodeType = System.Runtime.CompilerServices.MethodCodeType.IL), System.Security.SuppressUnmanagedCodeSecurity]
        public static float[] ToFloatArray(string value, string seperator, int numberofelements)
        {
            if (string.IsNullOrWhiteSpace(value))
                return new float[] { };

```
        float[] result;

        result = value.Split(',').Select(float.Parse).Take(numberofelements).ToArray();

        return result;
    }
```

}

public static class Algebra
{
/// <summary>

        /// Used to calculate the average of single values passed in.
        /// </summary>

        /// <param name="values">An array of single values.</param>
        /// <returns>Standard Deviation of a list of single values.</returns>
        /// <remarks></remarks>
        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.NoInlining,
            MethodCodeType = System.Runtime.CompilerServices.MethodCodeType.IL), System.Security.SuppressUnmanagedCodeSecurity]
        public static float StDev(params float[] values)
        {
            // Step 1: Average
            // Step 2: Take each value - by the average
            // Step 3: square
            // Step 4: take all add them up
            // Step 5: #sample minus by 1
            // Step 6: divide step 4 by  4
            int count = values.Count();
            float total = 0.0f;
            float average = 0.0f;
            float values_minus_average = 0.0f;
            float squareroot = 0.0f;

```
        int maxIndex = values.Count() - 1;
        for (int Index = 0; Index <= maxIndex; Index++)
        {
            float value = values[Index];
            total += value;
        }

        if (count > 0)
        {
            average = total / count;
        }

        maxIndex = values.Count() - 1;
        for (int Index = 0; Index <= maxIndex; Index++)
        {
            float value = values[Index];
            values_minus_average += ((value - average) * (value - average));
        }

        float stdevbase = 0.0f;

        if (count > 1)
        {
            stdevbase = (values_minus_average / (count - 1));
        }
        else
        {
            stdevbase = values_minus_average;
        }

        squareroot = (float)System.Math.Sqrt(stdevbase);

        return squareroot;
    }
```

}

**Comment by gabrielsimas** [comment]
in this line result = value.Split(',').Select(float.Parse).Take(numberofelements).ToArray();

Already tried to force the "Select float.parse" with lambdas within float.parse (p => p ...)? Could this help?

**Comment by lahma** [comment]
I'm doing a rude experiment with closing this, like what stale bot does, but maybe more human as I will probably actually react to feedback. As this issue has been stale for so long, I'll close it. If it's still an issue you would like to pursue, we can definitely reopen. 

With limited resources this is just something that we need to do. Thank you for your understanding.
