### ISSUE TITLE
CacheResult Key SpEl can't use #variableName

### ISSUE THREAD

**Issue by systembugtj** [spring-projects/spring-net#63]
Spring.net 2.0.0.40000
[CacheResult("AspNetCache", "'Address.Ip =' + #ipAddress", TimeToLive = "24:0:0")]  
 public Address SelectAddressByIp(string ipAddress)

It has exception "expect: LPAREN, found"

Check the code, it break at

match (POUND);
match(ID);
match(LPAREN);<-here

Look like the variable reference is not checked correctly.

**Comment by lahma** [comment]
I'm doing a rude experiment with closing this, like what stale bot does, but maybe more human as I will probably actually react to feedback. As this issue has been stale for so long, I'll close it. If it's still an issue you would like to pursue, we can definitely reopen. 

With limited resources this is just something that we need to do. Thank you for your understanding.
