### ISSUE TITLE
Unit Tests failing for .NET 4.0

### ISSUE THREAD

**Issue by vivf86** [spring-projects/spring-net#69]
For the .NET 4.0 build for the RC1 code, the following tests are failing in Spring.Core.Tests.2010:

Spring.Globalization.Formatters.CurrencyFormatterTests
-FormatUsingCustomSettings
-FormatUsingDefaults
-ParseUsingCustomSettings
-ParseUsingDefaults
Spring.Globalization.Formatters.DateTimeFormatterTests
-FormatUsingDefaults
-ParseUsingDefaults

I have verified on my machine commented these tests out on my machine and the build completes successfully. I haven't attempted to fix them because some of the assertions have funny characters in them and I'm not sure what's required there.

Also I'm not sure if this is machine specific. It's possible there are issues with my environment. However, I have compiled the milestone versions in the past with no issues.

Build log extract is included below.

            test:
            
            
            common.run-tests:
            
            
            common.run-tests.nunit:
            
                 [echo] Unit Testing Spring.NET, Spring.Core.Tests in C:\devenv\spring-net-spring-net-2.0.0-RC1/build/net/4.0/debug
                 [exec] Starting 'C:\devenv\spring-net-spring-net-2.0.0-RC1/packages/NUnit.Runners.2.6.1/tools/nunit-console-x86.exe (Spring.Core.Tests.dll /xml:Spring.Core.Tests.dll-TestResults.xml /framework:net-4.0 /nologo /noshadow)' in 'C:\devenv\spring-net-spring-net-2.0.0-RC1\build\net\4.0\debug'
                 [exec] ProcessModel: Default    DomainUsage: Single
                 [exec] Execution Runtime: net-4.0
                 [exec] ...........................................................................................................................................................................................................................................................................Source      : Spring.Context.Events.ConsoleListenerTests
                 [exec] Event fired : 7/03/2014 12:34:02 PM
                 [exec] ........................................................................................................................N.........................................N.......post process Spring.Objects.TestObject#91FC31
                 [exec] ...Spring.Context.Support.XmlApplicationContextTests+DestroyTester
                 [exec] ............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................F.F..F.F...F..F..................................................................................................................................................................................................................................................................................................................................................................................................init factory
                 [exec] .N............................................N........................N............................................................................DisposableClass.Dispose()
                 [exec] .N......N..............................................................................................................................N.......................................................................................................N...........................................................................................................................................................................N..N............................N....................................................................................................N....N........................................................................................................................N...................N.N........N................N.N..............................................................................................................................................................................................................................................................................................................................................................................................................................................
                 [exec] Tests run: 2666, Errors: 3, Failures: 3, Inconclusive: 0, Time: 20.8386908 seconds
                 [exec]   Not run: 20, Invalid: 0, Ignored: 20, Skipped: 0
                 [exec] 
                 [exec] Errors and Failures:
                 [exec] 1) Test Failure : Spring.Globalization.Formatters.CurrencyFormatterTests.FormatUsingCustomSettings
                 [exec]      String lengths are both 14. Strings differ at index 10.
                 [exec]   Expected: "1'23'4,00 ???."
                 [exec]   But was:  "1'23'4,00 ???."
                 [exec]   ---------------------^
                 [exec] 
                 [exec] at Spring.Globalization.Formatters.CurrencyFormatterTests.FormatUsingCustomSettings() in c:\devenv\spring-net-spring-net-2.0.0-RC1\test\Spring\Spring.Core.Tests\Globalization\Formatters\CurrencyFormatterTests.cs:line 153
                 [exec] 
                 [exec] 2) Test Failure : Spring.Globalization.Formatters.CurrencyFormatterTests.FormatUsingDefaults
                 [exec]      String lengths are both 13. Strings differ at index 9.
                 [exec]   Expected: "1.234,00 din."
                 [exec]   But was:  "1.234,00 Din."
                 [exec]   --------------------^
                 [exec] 
                 [exec] at Spring.Globalization.Formatters.CurrencyFormatterTests.FormatUsingDefaults() in c:\devenv\spring-net-spring-net-2.0.0-RC1\test\Spring\Spring.Core.Tests\Globalization\Formatters\CurrencyFormatterTests.cs:line 69
                 [exec] 
                 [exec] 3) Test Error : Spring.Globalization.Formatters.CurrencyFormatterTests.ParseUsingCustomSettings
                 [exec]    System.FormatException : Input string was not in a correct format.
                 [exec]    at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
                 [exec]    at System.Double.Parse(String s, NumberStyles style, IFormatProvider provider)
                 [exec]    at Spring.Globalization.Formatters.CurrencyFormatter.Parse(String value) in c:\devenv\spring-net-spring-net-2.0.0-RC1\src\Spring\Spring.Core\Globalization\Formatters\CurrencyFormatter.cs:line 205
                 [exec]    at Spring.Globalization.Formatters.CurrencyFormatterTests.ParseUsingCustomSettings() in c:\devenv\spring-net-spring-net-2.0.0-RC1\test\Spring\Spring.Core.Tests\Globalization\Formatters\CurrencyFormatterTests.cs:line 188
                 [exec] 
                 [exec] 4) Test Error : Spring.Globalization.Formatters.CurrencyFormatterTests.ParseUsingDefaults
                 [exec]    System.FormatException : Input string was not in a correct format.
                 [exec]    at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
                 [exec]    at System.Double.Parse(String s, NumberStyles style, IFormatProvider provider)
                 [exec]    at Spring.Globalization.Formatters.CurrencyFormatter.Parse(String value) in c:\devenv\spring-net-spring-net-2.0.0-RC1\src\Spring\Spring.Core\Globalization\Formatters\CurrencyFormatter.cs:line 205
                 [exec]    at Spring.Globalization.Formatters.CurrencyFormatterTests.ParseUsingDefaults() in c:\devenv\spring-net-spring-net-2.0.0-RC1\test\Spring\Spring.Core.Tests\Globalization\Formatters\CurrencyFormatterTests.cs:line 104
                 [exec] 
                 [exec] 5) Test Failure : Spring.Globalization.Formatters.DateTimeFormatterTests.FormatUsingDefaults
                 [exec]      Expected string length 16 but was 15. Strings differ at index 15.
                 [exec]   Expected: "14. avgust 2004."
                 [exec]   But was:  "14. avgust 2004"
                 [exec]   --------------------------^
                 [exec] 
                 [exec] at Spring.Globalization.Formatters.DateTimeFormatterTests.FormatUsingDefaults() in c:\devenv\spring-net-spring-net-2.0.0-RC1\test\Spring\Spring.Core.Tests\Globalization\Formatters\DateTimeFormatterTests.cs:line 71
                 [exec] 
                 [exec] 6) Test Error : Spring.Globalization.Formatters.DateTimeFormatterTests.ParseUsingDefaults
                 [exec]    System.FormatException : String was not recognized as a valid DateTime.
                 [exec]    at System.DateTimeParse.ParseExact(String s, String format, DateTimeFormatInfo dtfi, DateTimeStyles style)
                 [exec]    at System.DateTime.ParseExact(String s, String format, IFormatProvider provider, DateTimeStyles style)
                 [exec]    at Spring.Globalization.Formatters.DateTimeFormatter.Parse(String value) in c:\devenv\spring-net-spring-net-2.0.0-RC1\src\Spring\Spring.Core\Globalization\Formatters\DateTimeFormatter.cs:line 116
                 [exec]    at Spring.Globalization.Formatters.DateTimeFormatterTests.ParseUsingDefaults() in c:\devenv\spring-net-spring-net-2.0.0-RC1\test\Spring\Spring.Core.Tests\Globalization\Formatters\DateTimeFormatterTests.cs:line 100
                 [exec] 
                 [exec] 
                 [exec] Tests Not Run:
                 [exec] 1) Ignored : Spring.Context.Support.ResourceSetMessageSourceTests.GetNullResourceIn2PointOh
                 [exec]    See SPRNET-246
                 [exec] 2) Ignored : Spring.Context.Support.XmlApplicationContextTests.ContextWithInvalidLazyType
                 [exec]    Need to add Spring.TypeLoadException
                 [exec] 3) Ignored : Spring.Objects.Factory.DefaultListableObjectFactoryPerfTests.Test
                 [exec] 4) Ignored : Spring.Objects.Factory.DefaultListableObjectFactoryTests.CreateObjectWithCtorArgsOnPrototypeOutOfOrderArgs
                 [exec]    Ordering must now be strict when providing array of arguments for ctors
                 [exec] 5) Ignored : Spring.Objects.Factory.DefaultListableObjectFactoryTests.GetObjectWithCtorArgsOnPrototypeOutOfOrderArgs
                 [exec]    Ordering must now be strict when providing array of arguments for ctors
                 [exec] 6) Ignored : Spring.Objects.Factory.SPRNET_1338.CanAvoidLockContentionDuringObjectFactoryDisposal
                 [exec]    Test fails -- waiting for verification re: if bug exists in Java impl
                 [exec] 7) Ignored : Spring.Objects.Factory.Support.AutowireUtilsTests.GetTypeDifferenceWeightWithMismatchedLengths
                 [exec]    Investigate details of new type weight algorithm
                 [exec] 8) Ignored : Spring.Objects.Factory.Xml.EventWiringTests.EventWiringInstanceSinkToPrototypeSource
                 [exec]    SPRNET-21
                 [exec] 9) Ignored : Spring.Objects.Factory.Xml.XmlObjectDefinitionReaderTests.AutoRegistersWellknownNamespaceParser
                 [exec] 10) Ignored : Spring.Objects.ObjectWrapperTests.GetSetIndexerProperties
                 [exec] 11) Ignored : Spring.Objects.ObjectWrapperTests.GetValueOfCustomIndexerProperty
                 [exec] 12) Ignored : Spring.Objects.ObjectWrapperTests.SetIndexOutOfRangeFromListProperty
                 [exec]    Addition of elements to the list via index that is out of range is not supported anymore.
                 [exec] 13) Ignored : Spring.Pool.SimplePoolTests.PassivateBusyObjectsBeforeClose
                 [exec]    Cannot figure out why this is failing?
                 [exec] 14) Ignored : Spring.Pool.StessSimplePool.ScalingAgainstIncreasingNumberOfThreads
                 [exec]    a try for a stress
                 [exec] 15) Ignored : Spring.Reflection.Dynamic.DynamicFieldTests.CannotReadPrivateReadOnlyFieldIfNoReflectionPermission
                 [exec]    TODO: this works as expected when run using TD.NET & R# (in VS2k8), but fails with nant/NET 2.0 ?!?
                 [exec] 16) Ignored : Spring.Reflection.Dynamic.DynamicPropertyTests.BasePropertyTests.TestForRestrictiveGetter
                 [exec]    test N/A anymore due to System.Reflection.Emit.DynamicMethod
                 [exec] 17) Ignored : Spring.Reflection.Dynamic.DynamicPropertyTests.BasePropertyTests.TestForRestrictiveSetter
                 [exec]    test N/A anymore due to System.Reflection.Emit.DynamicMethod
                 [exec] 18) Ignored : Spring.Reflection.Dynamic.SafeFieldTests.DynamicFieldTests.CannotReadPrivateReadOnlyFieldIfNoReflectionPermission
                 [exec]    TODO: this works as expected when run using TD.NET & R# (in VS2k8), but fails with nant/NET 2.0 ?!?
                 [exec] 19) Ignored : Spring.Reflection.Dynamic.SafePropertyTests.BasePropertyTests.TestForRestrictiveGetter
                 [exec]    test N/A anymore due to System.Reflection.Emit.DynamicMethod
                 [exec] 20) Ignored : Spring.Reflection.Dynamic.SafePropertyTests.BasePropertyTests.TestForRestrictiveSetter
                 [exec]    test N/A anymore due to System.Reflection.Emit.DynamicMethod
                 [exec] 
            
            BUILD FAILED
            
            External Program Failed: C:\devenv\spring-net-spring-net-2.0.0-RC1/packages/NUnit.Runners.2.6.1/tools/nunit-console-x86.exe (return code was 6)
            
            Total time: 36.3 seconds.

**Comment by sbohlen** [comment]
Closing issue as machine-specific or other since .NET 4.0 tests pass on several other computers as well as the latest CI builds as well.
