### ISSUE TITLE
Make ExpressionParser public to allow, for example, expression formatting

### ISSUE THREAD

**Issue by jacargentina** [spring-projects/spring-net#76]
I'm using Spring.Core on my c# project, and the final user writes its scripts using the Expression language. A nice addition i want to provide is being able to "nice format" this scripts (indentation, new lines etc...) to make all expressions look nice and well formatted (a really big script can be confusing if not well formatted)

I think the best way to make this is use the ExpressionParser / (or lexer, i dont know exactly yet...) to get "the expression tree" from the text string, and then insert indentation, spaces, new lines, etc according to each tree node type (conditionals, sequences, etc)

As ExpressionParser is private, i cant acces it directly to achieve that. So that is why i'm propossing to make that class public.

**Comment by lahma** [comment]
I'm doing a rude experiment with closing this, like what stale bot does, but maybe more human as I will probably actually react to feedback. As this issue has been stale for so long, I'll close it. If it's still an issue you would like to pursue, we can definitely reopen. 

With limited resources this is just something that we need to do. Thank you for your understanding.
