### ISSUE TITLE
System.InvalidCastException : Unable to cast object of type from CompositeAopProxy

### ISSUE THREAD

**Issue by ynauls** [spring-projects/spring-net#98]
Thank you, I am troubleshooting a proxy issue this time. I swapped my proxy factory class from _NHibernate.ByteCode.Castle_ to _Spring.Data.NHibernate4_.  NHibernate.ByteCode.Castle doesn't support having identical interface name in different namespaces.  I can got passed this failure by swapping the factory to _Spring.Data.NHibernate4_, but now another unit test is failing when is trying to cast a CompositeAopProxy to the proxy type of the class (an interface).   I tried using NHibernate.Initialize to initialize the proxy but no luck.  any tips would be very helpful.

```
// changed from 
<entry key="proxyfactory.factory_class" value="NHibernate.ByteCode.Castle.ProxyFactoryFactory, NHibernate.ByteCode.Castle"/>

// to this
<entry key="proxyfactory.factory_class" value="Spring.Data.NHibernate.Bytecode.ProxyFactoryFactory, Spring.Data.NHibernate4"/>

```

```
// both interfaces ISquare and ICircle inherit from IShape, so it creates a composite AOP proxy of ISquare and ICircle,  
Both interfaces share a property called SomeProperty in my example. I ensured that the proxy belongs to an instance of type Square
System.InvalidCastException : Unable to cast object of type 'SomeNameSpace.Square' to type 'SomeNameSpace.ICircle'.
   at _dynamic_SomeNameSpace.ICircle.get_SomeProperty(Object, Object[])
   at Spring.Reflection.Dynamic.SafeMethod.Invoke(Object target, Object[] arguments)
   at Spring.Data.NHibernate.Bytecode.LazyInitializer.Invoke(IMethodInvocation invocation)
   at Spring.Aop.Framework.AbstractMethodInvocation.Proceed()
   at Spring.Aop.Framework.DynamicProxy.AdvisedProxy.Invoke(Object proxy, Object target, Type targetType, MethodInfo targetMethod, MethodInfo proxyMethod, Object[] args, IList interceptors)
   at CompositionAopProxy_4127a6f79e61431eb15f3b096c68144f.get_SomeProperty()
```

**Comment by piolo108** [comment]
Update, I swapped the factory to use NH4 Default factory
'''
<entry key="proxyfactory.factory_class" value="NHibernate.Bytecode.DefaultProxyFactoryFactory, NHibernate"/>
'''

It also fails, stack trace below

'''
System.Reflection.TargetException : Object does not match target type.
   at System.Reflection.RuntimeMethodInfo.CheckConsistency(Object target)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at NHibernate.Proxy.DefaultLazyInitializer.Intercept(InvocationInfo info)
   at INHibernateProxyProxy.get_SomeProperty()
'''

**Comment by piolo108** [comment]
Update, I swapped the factory to use NHibernate.ByteCode.Castle (3.1.0.4000) and no errors.

```
<entry key="proxyfactory.factory_class" value="NHibernate.ByteCode.Castle.ProxyFactoryFactory, NHibernate.ByteCode.Castle"/>
```

Going to try to dig through the code.

**Comment by lahma** [comment]
AFAIK the NHibernate team is more geared towards using their default proxy factory nowadays instead of using custom one. We should weight whether it's beneficial to have custom proxy factory provided with Spring with NH 3.3+...

**Comment by sbohlen** [comment]
@lahma:

What's the downside to our choosing to rely upon NHibernate's own ProxyFactory implementation instead of our own --?  Is it just "we end up with two different proxy engines running SxS" (which is simply inefficient)?

I suppose in theory this would make it impossible for the SPRNET container to apply advice to NH-persisted objects, but TBH that seems to me to be a somewhat contrived use-case in the first place...(?)

**Comment by sbohlen** [comment]
@piolo108 :

It looks as if you're indicating that proxies from both the NH internal proxy factory and the SPRNET proxy factory fail your test(s) but that proxies from the Castle proxy factory _do_ support your use-case.

Have you raised this with the NHibernate project yet?  And if so, have they offered any input/feedback?

**Comment by piolo108** [comment]
@sbohlen, I did, below is the reference pull request I created to reproduce the error in their latest revision:

https://github.com/nhibernate/nhibernate-core/pull/397

**Comment by lahma** [comment]
@sbohlen What we would lose is the injection and advice capabilities (container generated entities). As with MVC the code uses find names by type functionality that is slow. So I'd say it's not a good idea at the moment use container created instances any way.

**Comment by lahma** [comment]
I'm doing a rude experiment with closing this, like what stale bot does, but maybe more human as I will probably actually react to feedback. As this issue has been stale for so long, I'll close it. If it's still an issue you would like to pursue, we can definitely reopen. 

With limited resources this is just something that we need to do. Thank you for your understanding.
